/**
 * pdfGenerator.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Reusable PDF generation utility for MoneyMap.
 *
 * Usage:
 *   import { generateFinancialReport } from "../utils/pdfGenerator";
 *   await generateFinancialReport({ currencySymbol: "₹", userName: "John" });
 *
 * Dependencies: jspdf, jspdf-autotable  (already installed)
 * ─────────────────────────────────────────────────────────────────────────────
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  getDashboardSummary,
  getCategorySummary,
  getMonthlySummary,
  getRecentTransactions,
} from "../services/expenseService";

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Strip emoji / non-Latin-1 characters so jsPDF standard fonts don't render boxes.
 * We keep ASCII printable range + common symbols (₹ is replaced by "Rs." below).
 */
const sanitize = (str) =>
  String(str ?? "")
    .replace(/[\u{1F000}-\u{1FFFF}]/gu, "")   // emoji block
    .replace(/[^\x00-\xFF]/g, "")              // anything outside Latin-1
    .trim();

/** Format a number as currency, e.g. "Rs. 1,23,456" */
const fmtCurrency = (amount, symbol = "Rs.") =>
  `${symbol} ${Number(amount ?? 0).toLocaleString("en-IN")}`;

/** Format a date string as "DD MMM YYYY" */
const fmtDate = (dateStr) => {
  const d = new Date(dateStr ?? Date.now());
  const valid = isNaN(d.getTime()) ? new Date() : d;
  return valid.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

/** Capitalise first letter */
const cap = (s) => String(s ?? "").charAt(0).toUpperCase() + String(s ?? "").slice(1);

// ─── Layout constants ─────────────────────────────────────────────────────────
const MARGIN    = 14;
const PAGE_W    = 210; // A4 mm
const CONTENT_W = PAGE_W - MARGIN * 2;
const BRAND     = "#10B981"; // emerald-500
const DARK      = "#0F172A";
const MUTED     = "#64748B";

// ─── Section heading helper ───────────────────────────────────────────────────
const drawSectionHeading = (doc, text, y) => {
  doc.setFillColor(BRAND);
  doc.rect(MARGIN, y, 3, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(DARK);
  doc.text(text, MARGIN + 6, y + 5);
  return y + 12;
};

// ─── Footer helper ────────────────────────────────────────────────────────────
const drawFooter = (doc) => {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageH = doc.internal.pageSize.getHeight();
    doc.setDrawColor(230, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, pageH - 12, PAGE_W - MARGIN, pageH - 12);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(
      `Generated by MoneyMap  ·  ${new Date().getFullYear()}`,
      MARGIN,
      pageH - 6
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      PAGE_W - MARGIN,
      pageH - 6,
      { align: "right" }
    );
  }
};

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Fetches fresh report data and downloads a PDF.
 *
 * @param {Object} options
 * @param {string} [options.currencySymbol="₹"]  — Display symbol (PDF uses "Rs.")
 * @param {string} [options.userName=""]          — User's name for the header
 */
export const generateFinancialReport = async ({
  currencySymbol = "₹",
  userName = "",
} = {}) => {
  // ── 1. Fetch all data ──────────────────────────────────────────────────────
  const [summaryData, categoryData, monthlyData, recentData] =
    await Promise.all([
      getDashboardSummary(),
      getCategorySummary(),
      getMonthlySummary(),
      getRecentTransactions(),
    ]);

  // Normalise responses -------------------------------------------------------
  const summary = {
    totalIncome:      Number(summaryData?.totalIncome      ?? 0),
    totalExpense:     Number(summaryData?.totalExpense      ?? 0),
    balance:          Number(summaryData?.balance           ?? 0),
    transactionCount: Number(summaryData?.transactionCount  ?? 0),
  };

  // category summary may arrive as { categorySummary: { "Food": 1200, … } }
  const rawCategories =
    categoryData?.categorySummary ?? categoryData ?? {};
  const categories = Object.entries(rawCategories)
    .filter(([, v]) => Number(v) > 0)
    .sort((a, b) => Number(b[1]) - Number(a[1]));

  // monthly summary may arrive as an array or an object map
  let monthlyRows = [];
  if (Array.isArray(monthlyData?.monthlySummary ?? monthlyData)) {
    monthlyRows = (monthlyData?.monthlySummary ?? monthlyData).map((m) => ({
      month:   m.month ?? m._id ?? "",
      income:  Number(m.income  ?? 0),
      expense: Number(m.expense ?? 0),
    }));
  } else if (typeof (monthlyData?.monthlySummary ?? monthlyData) === "object") {
    monthlyRows = Object.entries(monthlyData?.monthlySummary ?? monthlyData).map(
      ([month, data]) => ({
        month,
        income:  Number(data?.income  ?? data ?? 0),
        expense: Number(data?.expense ?? 0),
      })
    );
  }

  const recentTransactions = Array.isArray(recentData?.transactions)
    ? recentData.transactions
    : Array.isArray(recentData)
    ? recentData
    : [];

  // ── 2. Create PDF ──────────────────────────────────────────────────────────
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

  // ─── Cover / Header block ─────────────────────────────────────────────────
  // Green bar at top
  doc.setFillColor(BRAND);
  doc.rect(0, 0, PAGE_W, 28, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor("#FFFFFF");
  doc.text("MoneyMap Financial Report", MARGIN, 13);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#D1FAE5");
  const now = new Date();
  const genLabel = `Generated on ${fmtDate(now)}${userName ? "  ·  " + sanitize(userName) : ""}`;
  doc.text(genLabel, MARGIN, 22);

  let cursorY = 38;

  // ─── Section 1: Financial Summary ─────────────────────────────────────────
  cursorY = drawSectionHeading(doc, "Financial Summary", cursorY);

  // 2×2 grid of metric boxes
  const boxW = (CONTENT_W - 6) / 2;
  const boxH = 18;
  const metrics = [
    { label: "Total Income",      value: fmtCurrency(summary.totalIncome),       color: "#059669" },
    { label: "Total Expense",     value: fmtCurrency(summary.totalExpense),       color: "#EF4444" },
    { label: "Current Balance",   value: fmtCurrency(summary.balance),            color: "#3B82F6" },
    { label: "Total Transactions",value: String(summary.transactionCount),        color: DARK      },
  ];

  metrics.forEach((m, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x   = MARGIN + col * (boxW + 6);
    const y   = cursorY + row * (boxH + 4);

    // card bg
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, y, boxW, boxH, 2, 2, "F");
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, boxW, boxH, 2, 2, "S");

    // colored left accent
    doc.setFillColor(m.color);
    doc.rect(x, y, 2, boxH, "F");

    // label
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(MUTED);
    doc.text(m.label.toUpperCase(), x + 6, y + 6);

    // value
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(m.color);
    doc.text(m.value, x + 6, y + 14);
  });

  cursorY += 2 * (boxH + 4) + 8;

  // ─── Section 2: Category Summary ─────────────────────────────────────────
  cursorY = drawSectionHeading(doc, "Category Summary", cursorY);

  if (categories.length > 0) {
    autoTable(doc, {
      startY: cursorY,
      margin: { left: MARGIN, right: MARGIN },
      head: [["#", "Category", "Amount (Rs.)", "% of Total Expense"]],
      body: categories.map(([cat, amount], idx) => {
        const pct =
          summary.totalExpense > 0
            ? ((Number(amount) / summary.totalExpense) * 100).toFixed(1) + "%"
            : "—";
        return [
          String(idx + 1),
          sanitize(cat),
          fmtCurrency(amount),
          pct,
        ];
      }),
      styles: {
        fontSize: 9,
        cellPadding: 3,
        textColor: DARK,
        lineColor: [226, 232, 240],
        lineWidth: 0.25,
      },
      headStyles: {
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8.5,
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {
        0: { cellWidth: 10, halign: "center" },
        2: { halign: "right" },
        3: { halign: "right" },
      },
      tableLineColor: [226, 232, 240],
      tableLineWidth: 0.25,
      showHead: "everyPage",
    });
    cursorY = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No category data available.", MARGIN, cursorY + 4);
    cursorY += 14;
  }

  // ─── Section 3: Monthly Summary ──────────────────────────────────────────
  // Check if we need a new page
  if (cursorY > 230) { doc.addPage(); cursorY = 18; }

  cursorY = drawSectionHeading(doc, "Monthly Summary", cursorY);

  if (monthlyRows.length > 0) {
    autoTable(doc, {
      startY: cursorY,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Month", "Income (Rs.)", "Expense (Rs.)", "Net Savings (Rs.)"]],
      body: monthlyRows.map((r) => [
        sanitize(r.month),
        fmtCurrency(r.income),
        fmtCurrency(r.expense),
        fmtCurrency(r.income - r.expense),
      ]),
      styles: {
        fontSize: 9,
        cellPadding: 3,
        textColor: DARK,
        lineColor: [226, 232, 240],
        lineWidth: 0.25,
      },
      headStyles: {
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8.5,
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
      },
      tableLineColor: [226, 232, 240],
      tableLineWidth: 0.25,
      showHead: "everyPage",
      // Colour net savings cell red if negative
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 3) {
          const val = monthlyRows[data.row.index];
          if (val && val.income - val.expense < 0) {
            data.cell.styles.textColor = [239, 68, 68];
          } else {
            data.cell.styles.textColor = [5, 150, 105];
          }
        }
      },
    });
    cursorY = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No monthly data available.", MARGIN, cursorY + 4);
    cursorY += 14;
  }

  // ─── Section 4: Recent Transactions ──────────────────────────────────────
  if (cursorY > 220) { doc.addPage(); cursorY = 18; }

  cursorY = drawSectionHeading(doc, "Recent Transactions", cursorY);

  if (recentTransactions.length > 0) {
    autoTable(doc, {
      startY: cursorY,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Date", "Title", "Category", "Type", "Amount (Rs.)"]],
      body: recentTransactions.map((t) => [
        fmtDate(t.date),
        sanitize(cap(t.title)),
        sanitize(t.category),
        cap(t.type ?? "expense"),
        (t.type === "income" ? "+" : "-") + fmtCurrency(t.amount),
      ]),
      styles: {
        fontSize: 8.5,
        cellPadding: 3,
        textColor: DARK,
        lineColor: [226, 232, 240],
        lineWidth: 0.25,
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8.5,
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {
        0: { cellWidth: 24 },
        1: { cellWidth: 45 },
        3: { cellWidth: 20, halign: "center" },
        4: { halign: "right", cellWidth: 32 },
      },
      tableLineColor: [226, 232, 240],
      tableLineWidth: 0.25,
      showHead: "everyPage",
      // Colour amount column by type
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 4) {
          const t = recentTransactions[data.row.index];
          data.cell.styles.textColor =
            t?.type === "income" ? [5, 150, 105] : [239, 68, 68];
          data.cell.styles.fontStyle = "bold";
        }
        if (data.section === "body" && data.column.index === 3) {
          const t = recentTransactions[data.row.index];
          data.cell.styles.textColor =
            t?.type === "income" ? [5, 150, 105] : [239, 68, 68];
        }
      },
    });
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No recent transactions available.", MARGIN, cursorY + 4);
  }

  // ─── Footer on every page ─────────────────────────────────────────────────
  drawFooter(doc);

  // ─── Save ─────────────────────────────────────────────────────────────────
  const dateTag = now.toISOString().slice(0, 10); // YYYY-MM-DD
  doc.save(`MoneyMap_Report_${dateTag}.pdf`);
};
